### ISSUE TITLE
Animated Optimum/Approximate Solution

### ISSUE THREAD

**Issue by arkaray** [sharmaeklavya2/packing-game#4]
Let the user view the optimum/approximate solution with the movements to the bin or knapsack are shown using some animation.
A brute force optimum algorithm should be enough when there are smaller number of items. When there are a large number of items a switch to an approximate solution can be made.
This can be done in two ways:
1. An animated version can be shown after a person finishes solving
2. An animated version can run in parallel with the human solver.

(This is going to take considerable amount of time)

**Comment by sharmaeklavya2** [comment]
I suppose it would be "game over" when the user asks for the optimum solution.

We can also get lower-bounds on the solution, like ceil(area), and see if the user used that many bins. The current random instance generator isn't good enough, so I'm usually able to meet this bound.

**Comment by sharmaeklavya2** [comment]
Depends on #5.

**Comment by arkaray** [comment]
This is what a button like "I give up; Show me the solution" needs to do. Therefore, #5 depends on this not the other way.

**Comment by sharmaeklavya2** [comment]
Actually both depend on each other, but this depends more on #5 than the other way around. For this feature to be available to the end-user, a toolbar/sidebar must exist where we can add a "show me the solution" button, so this issue depends on #5. #5 doesn't strictly depend on this issue, since we can create a toolbar without such a button.

**Comment by sharmaeklavya2** [comment]
We can implement the core functionality of this feature and expose it as a function callable from the developer console. To do this, we need to figure out the position of each item and then repeatedly call `ItemUI.attach`. This part doesn't depend on #5.

**Comment by sharmaeklavya2** [comment]
I think animation isn't useful, especially for large instances. I have added the ability to see the output of multiple approximation algorithms.
