### ISSUE TITLE
Choose an interface for the user to manage the game

### ISSUE THREAD

**Issue by sharmaeklavya2** [sharmaeklavya2/packing-game#5]
We'll need a place to add buttons like "I give up; Show me the solution", "put the items back", "load a new game", "show me the instructions", etc. We can probably have a navbar at the top for this.

For the "load a new game" option, we can have a dropdown/pop-up that allows the user to choose from a preset game (see the `levels` directory) or specify parameters for the random instance generator.

This issue is important, since almost all functionality that requires user interaction needs a place for the elements/buttons.

List of UI elements needed in toolbar/sidebar/popup:

- [x] Load new game.
- [x] Give up; show solution.
- [x] Put items back in inventory.

**Comment by arkaray** [comment]
This issue is broad and open ended. So, don't mark anything as it's duplicate.

Just reference this issue whenever something relates to this.

**Comment by arkaray** [comment]
We need to maintain a running list of buttons/options we need. How are we supposed to do that?

One solution was to have them as separate issues referencing this.

**Comment by sharmaeklavya2** [comment]
If only adding a button is pending (for example, in #7), then no need for a separate issue. If the core functionality for that button/option is not yet implemented (as in #1), then open a separate issue.

If you don't know if a feature's core functionality is implemented or not, open a new issue. AFAIK, issues have been raised for all implemented features that don't have a UI, so other feature requests are likely to not be already implemented.

**Comment by sharmaeklavya2** [comment]
We will maintain a running list in the first comment of this issue. Comment in this thread if you want any items added/removed. Once the toolbar is implemented and the basic set of UI elements is added, we'll use separate issues for subsequent UI elements.
