### ISSUE TITLE
[UI] Add dark theme

### ISSUE THREAD

**Issue by sharmaeklavya2** [sharmaeklavya2/packing-game#9]
Probably the only thing we need to do is to add CSS rules in `@media (prefers-color-scheme: dark)`.

**Comment by nikldev0** [comment]
Hi, the game looks really cool, can I help out with this issue?

**Comment by sharmaeklavya2** [comment]
Sure! It's great that you want to help out.

**Comment by nikldev0** [comment]
Let me know @sharmaeklavya2 if you're happy with it or want something tweaked :)
